name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
   cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm ci
          npm install cypress-real-events --save-dev
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with: 
          browser: chrome
          spec: |
            cypress/e2e/sendInContactForm.cy.ts,
            cypress/e2e/searchInBlog.cy.ts
          config: |
            reporter=junit,
            reporterOptions.mochaFile=reports/junit-[hash].xml,
            reporterOptions.toConsole=true
        continue-on-error: true
            
      - name: Upload Cypress Videos
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore

      - name: Upload Cypress Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
      - name: Debug - Check what files were created
        if: always()
        run: |
          echo "=== Current directory ==="
          pwd
          ls -la
          
          echo "=== Looking for reports directory ==="
          find . -name "reports" -type d 2>/dev/null || echo "No reports directory found"
          
          echo "=== Looking for any XML files ==="
          find . -name "*.xml" -type f 2>/dev/null || echo "No XML files found anywhere"
          
          echo "=== Looking for junit files ==="
          find . -name "*junit*" -type f 2>/dev/null || echo "No junit files found"
          
          echo "=== Tree view (if available) ==="
          tree . 2>/dev/null || ls -R   

          echo "=== Contents of reports directory ==="  
      - name: Python setup
        if: always()
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: TestRail CLI upload results from test execution
        if: always()
        run: |
          XML_FILE=$(find . -name "*.xml" -type f | head -1)
          echo "XML file found: $XML_FILE"
          pip install trcli
          trcli -y \
            -h https://ostoja24.testrail.io/ \
            --project "Wyrodek Test Project" \
            -u tomasz.ostojski@protonmail.com \
            -p Ostoja24! \
            parse_junit \
            --title "Automated Tests from GitHub workflow and Cypress" \
            --run-description ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} \
            -f "reports/junit*.xml"
